### ISSUE TITLE
Checklist of features

### ISSUE THREAD

**Issue by yamiryu** [Ultimates1/employee-management-system#25]
- [x] Login

- [x] Forgot ID/password

- [x] Reset password

- [x] Home

- [x] Profile

   - [x] Employee - View own

- [x] Leave Request

   - [x] Employee - View own

- [x] Workflow

   - [x] Approve/request/reject leave requests

- [x] Timesheet

- [x] Project Management

   - [x] Create project

   - [x] Add employees
